// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nwFp0FRu212lkUck6nXc19X49dDpO3A',
    appId: '1:293040164997:web:ab9164457c353840b1d9ec',
    messagingSenderId: '293040164997',
    projectId: 'atplace-34a86',
    authDomain: 'atplace-34a86.firebaseapp.com',
    storageBucket: 'atplace-34a86.appspot.com',
    measurementId: 'G-GQ8TT6J4WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJODE1igkHH-53CUEw67v-4DRihbYtBXY',
    appId: '1:293040164997:android:a40d38a8005ddbaab1d9ec',
    messagingSenderId: '293040164997',
    projectId: 'atplace-34a86',
    storageBucket: 'atplace-34a86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP8m5AriMV52zHirTDd7Ai242TKtmfhws',
    appId: '1:293040164997:ios:07692e87f5568f78b1d9ec',
    messagingSenderId: '293040164997',
    projectId: 'atplace-34a86',
    storageBucket: 'atplace-34a86.appspot.com',
    iosClientId: '293040164997-tjehffkqk80hv52pakfevt6kcljjqv86.apps.googleusercontent.com',
    iosBundleId: 'com.example.atplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP8m5AriMV52zHirTDd7Ai242TKtmfhws',
    appId: '1:293040164997:ios:07692e87f5568f78b1d9ec',
    messagingSenderId: '293040164997',
    projectId: 'atplace-34a86',
    storageBucket: 'atplace-34a86.appspot.com',
    iosClientId: '293040164997-tjehffkqk80hv52pakfevt6kcljjqv86.apps.googleusercontent.com',
    iosBundleId: 'com.example.atplace',
  );
}
